# Uncomment to activate debugging from here
# set -x

if [ -z $ZSH_CACHE_DIR ]; then
  ZSH_CACHE_DIR=~/.cache
fi

# Load oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
. $ZSH/oh-my-zsh.sh

# Load antigen
. $HOME/.antigen/antigen.zsh
antigen init $HOME/.antigenrc

# Loads config files present in ~/.zsh/configs/pre, ~/.zsh/configs, and ~/.zsh/configs/post
# These are loaded first, second, and third, respectively.

_dir_functiond=$HOME/.zsh/function.d
_dir_aliasd=$HOME/.zsh/alias.d
_dir_configd=$HOME/.zsh/config.d

for _dir in $_dir_functiond $_dir_aliasd $_dir_configd/pre $_dir_configd $_dir_configd/post; do

  if [ -d $_dir ]; then
    # Load each .zsh file in $_dir, if $_dir exists or is symbolic link
    for config in $_dir/*.zsh; do
      . $config
    done
  fi

done

_conf_zshrc_local = $HOME/.zshrc_local
_conf_fzf = $HOME/.fzf.zsh

for _conf in $_conf_zshrc_local $_conf_fzf; do
  [ -e $_conf ] && . $_conf
done
